# Data Cleaning

*Author: Holly Bok*

### Importing Packages and Data

In [1]:
# Importing packages

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [2]:
# Importing the train and test datasets
# Checking the first 3 rows of the train datafame 

train = pd.read_csv('datasets/train.csv')
test = pd.read_csv('datasets/test.csv')
train.head(3)

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000

### Data Cleaning / Data Type Conversions

In [3]:
# Checking column types and identifying which columns are listed as objects that can be converted to integers /
# floats or vice versa

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 81 columns):
Id                 2051 non-null int64
PID                2051 non-null int64
MS SubClass        2051 non-null int64
MS Zoning          2051 non-null object
Lot Frontage       1721 non-null float64
Lot Area           2051 non-null int64
Street             2051 non-null object
Alley              140 non-null object
Lot Shape          2051 non-null object
Land Contour       2051 non-null object
Utilities          2051 non-null object
Lot Config         2051 non-null object
Land Slope         2051 non-null object
Neighborhood       2051 non-null object
Condition 1        2051 non-null object
Condition 2        2051 non-null object
Bldg Type          2051 non-null object
House Style        2051 non-null object
Overall Qual       2051 non-null int64
Overall Cond       2051 non-null int64
Year Built         2051 non-null int64
Year Remod/Add     2051 non-null int64
Roof Style         2051 non-null object
Roof Matl          2051 non-null object
Exterior 1st       2051 non-null object
Exterior 2nd       2051 non-null object
Mas Vnr Type       2029 non-null object
Mas Vnr Area       2029 non-null float64
Exter Qual         2051 non-null object
Exter Cond         2051 non-null object
Foundation         2051 non-null object
Bsmt Qual          1996 non-null object
Bsmt Cond          1996 non-null object
Bsmt Exposure      1993 non-null object
BsmtFin Type 1     1996 non-null object
BsmtFin SF 1       2050 non-null float64
BsmtFin Type 2     1995 non-null object
BsmtFin SF 2       2050 non-null float64
Bsmt Unf SF        2050 non-null float64
Total Bsmt SF      2050 non-null float64
Heating            2051 non-null object
Heating QC         2051 non-null object
Central Air        2051 non-null object
Electrical         2051 non-null object
1st Flr SF         2051 non-null int64
2nd Flr SF         2051 non-null int64
Low Qual Fin SF    2051 non-null int64
Gr Liv Area        2051 non-null int64
Bsmt Full Bath     2049 non-null float64
Bsmt Half Bath     2049 non-null float64
Full Bath          2051 non-null int64
Half Bath          2051 non-null int64
Bedroom AbvGr      2051 non-null int64
Kitchen AbvGr      2051 non-null int64
Kitchen Qual       2051 non-null object
TotRms AbvGrd      2051 non-null int64
Functional         2051 non-null object
Fireplaces         2051 non-null int64
Fireplace Qu       1051 non-null object
Garage Type        1938 non-null object
Garage Yr Blt      1937 non-null float64
Garage Finish      1937 non-null object
Garage Cars        2050 non-null float64
Garage Area        2050 non-null float64
Garage Qual        1937 non-null object
Garage Cond        1937 non-null object
Paved Drive        2051 non-null object
Wood Deck SF       2051 non-null int64
Open Porch SF      2051 non-null int64
Enclosed Porch     2051 non-null int64
3Ssn Porch         2051 non-null int64
Screen Porch       2051 non-null int64
Pool Area          2051 non-null int64
Pool QC            9 non-null object
Fence              400 non-null object
Misc Feature       65 non-null object
Misc Val           2051 non-null int64
Mo Sold            2051 non-null int64
Yr Sold            2051 non-null int64
Sale Type          2051 non-null object
SalePrice          2051 non-null int64
dtypes: float64(11), int64(28), object(42)
memory usage: 1.3+ MB

In [4]:
# Converting Property ID from integer to object

train['PID'] = train['PID'].astype(object)

In [5]:
# Defining a function that will input the name of a column and replace the 'Ex', 'Gd', 'TA', 'Fa', and 'Po' rating
# with a 0-5 rank. This conversion function will be useful for several variables currently listed as objects.
# NaN values are replaced with a score of 0
# Column type is converted to integer. 

def rank_column(column):   
    train[column] = train[column].str.replace('Ex', '5')
    train[column] = train[column].str.replace('Gd', '4')
    train[column] = train[column].str.replace('TA', '3')
    train[column] = train[column].str.replace('Fa', '2')
    train[column] = train[column].str.replace('Po', '1')
    train[column] = train[column].fillna(0)
    train[column] = train[column].astype(int)
    return

In [6]:
# Using rank_column() to rank columns for Exterior Quality, Exterior Condition, Heating Quality, Kitchen Quality, 
# Garage Quality, Garage Condition, Pool Quality, and Basement condition 

rank_column('Exter Qual')
rank_column('Exter Cond')
rank_column('Heating QC')
rank_column('Kitchen Qual')
rank_column('Garage Qual')
rank_column('Garage Cond')
rank_column('Pool QC')
rank_column('Bsmt Cond')

In [7]:
# Manually ranking Paved Drive and converting datatype to integer
# Manually ranked variables have ranking systems that will not be converted correctly using rank_column()
# Paved drives are ranked at 3, partial pavement drives at 2, and gravel/ dirt drives at 1

train['Paved Drive'] = train['Paved Drive'].str.replace('Y', '3')
train['Paved Drive'] = train['Paved Drive'].str.replace('P', '2')
train['Paved Drive'] = train['Paved Drive'].str.replace('N', '1')
train['Paved Drive'] = train['Paved Drive'].astype(int)

In [8]:
# Manually ranking Functionality and converting datatype to integer
# Typical is ranked at 6, minor deductions at 5, moderate deductions at 4, major deductions at 3, severely
# damaged at 2, and salvage only at 1 

train['Functional'] = train['Functional'].str.replace('Typ', '6')
train['Functional'] = train['Functional'].str.replace('Min2', '5')
train['Functional'] = train['Functional'].str.replace('Min1', '5')
train['Functional'] = train['Functional'].str.replace('Mod', '4')
train['Functional'] = train['Functional'].str.replace('Maj1', '3')
train['Functional'] = train['Functional'].str.replace('Maj2', '3')
train['Functional'] = train['Functional'].str.replace('Sev', '2')
train['Functional'] = train['Functional'].str.replace('Sal', '1')
train['Functional'] = train['Functional'].astype(int)

In [9]:
# Manually ranking Garage Finish and converting datatype to integer
# Finished is ranked at 3, rough finish at 2, unfinished at 1. 
# No garage is ranked at 0.

train['Garage Finish'] = train['Garage Finish'].str.replace('Fin', '3')
train['Garage Finish'] = train['Garage Finish'].str.replace('RFn', '2')
train['Garage Finish'] = train['Garage Finish'].str.replace('Unf', '1')
train['Garage Finish'] = train['Garage Finish'].fillna(0)
train['Garage Finish'] = train['Garage Finish'].astype(int)

In [10]:
# Creating a csv file with cleaned data for use in 02 Linear Regression and 03 Regularization

clean_train = train
clean_train.to_csv('datasets/clean_train.csv', index=False)